version: "2"
volumes:
  pgdb:
networks:
  main:
    driver: bridge
services:
  webserver:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - selenium
    networks:
      - main
    container_name: webserver
    volumes:
      - .:/app/fathom-training-server
    env_file: docker/webserver.env
    command: ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  selenium:
    image: selenium/standalone-firefox
    networks:
      - main
    container_name: selenium

  # -----------------------------
  # External services
  # -----------------------------

  postgres:
    image: postgres:10
    ports:
      - 8574:5432
    environment:
      POSTGRES_USER: fathom-server
      POSTGRES_PASSWORD: fathom-server
      POSTGRES_DB: fathom-server
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - main
    container_name: postgres
